spring:
  profiles:
    active: dev

  application:
    name: my-security-learning

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_security?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root312
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikariDataSource


  redis:
    port: 6379
    host: localhost
    database: 0
    timeout: 10000 # 连接超时时间，单位：毫秒
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 自定义的token相关信息
jwt:
  tokenSignKey: rgebeeit32e21grd32d54oe65ryesw23 # 密钥
  tokenExpiration: 604800 # 有效期7天，单位：秒

#自定义属性，配置私钥路径
rsa:
  key:
    privateKeyPath: D:\auth_key\rsa_key
    publicKeyPath: D:\auth_key\rsa_key.pub
